### ISSUE TITLE
Add proper plural configuration

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/potools#7]
Unfortunately `potools` doesn't add any proper plural configuration header to the pofiles so errors like https://sentry.prod.mozaws.net/operations/olympia-dev/issues/608333/ keep occouring whenever we re-extract.

Let's maybe add them to the headers. See https://github.com/mozilla/addons-server/commit/aba4b7c860233a78c71384746bac5427edb80484 for an example configuration.

**Comment by muffinresearch** [comment]
I think that's due to them being missing from the addons-server pot file since potools will reproduce whatever it is handed. It might be easier to fix it there since defaulting to an english plural forms if missing might not be right for everyone if this got wider use where english wasn't a default locale. 

FWIW We have [it defined in addons-frontend](https://github.com/mozilla/addons-frontend/blob/master/locale/templates/LC_MESSAGES/amo.pot#L12) and it causes no problems, anyone that needs to can override it and msgmerge doesn't trample it if defined.
